### ISSUE TITLE
Quelques erreurs dans AC

### ISSUE THREAD

**Issue by ifcenens** [R-Alexandre/Cours-S2#2]
1)page 13
Au milieu, après le rang « et » :
l'intégral de gauche <= **4^n** * l'intégral de droite

2)page 13
Près de la fin, dans l'équation après la phrase « Alors pour tout n ≥ 0, », l'intégrande du terme qui vaut 0 :
**f(z0)** + (z − z0)f′(z0)

3)page 22
Coquille dans la première ligne :
Alors Cδ′ coïncide avec C à **part** sur le « couloir de largeur δ ».

**Comment by R-Alexandre** [comment]
Merci !
