### ISSUE TITLE
Quelques erreurs dans AC

### ISSUE THREAD

**Issue by ifcenens** [R-Alexandre/Cours-S2#3]
1)page 21 théorème 1.1
f(z) = 1/2iπ * **∫f(w)/(w-z)dw**

2)page 26 corollaire 2.6
Je crois il vaudrait mieux écrire « **Soient** f et g **deux fonctions** holomorphes » ou bien changer la première virgule en un point.

3)page 26 théorème 3.2
une suite de fonctions holomorphes qui convergent **uniformément** vers f

4)page 28 définition 1.1
tel que f **soit** définie

5)page 30 théorème 1.8
tels que pour tout z ∈ Ω \ {z0}, on **ait**

6)page 36, dans la preuve du théorème 3.5, après le rang « On regarde »
**g : z→1/(f(z)-w)**

7)page 38 théorème 4.2
Ce n'est pas plutôt « f et f+g ont **le même nombre** de zéros » ?

Je m'excuse en avance au cas où j'aurais tort.

**Comment by R-Alexandre** [comment]
Corrigé, merci.
