### ISSUE TITLE
Les preuves

### ISSUE THREAD

**Issue by ifcenens** [R-Alexandre/Cours-S2#4]
Excusez-moi, juste une petite question : pourquoi avez-vous supprimé les preuves des théorèmes ?

**Comment by R-Alexandre** [comment]
L'historique est disponible en cas de besoin.

**Comment by ifcenens** [comment]
Page 45, théorème 1.1, l'expression de an, l'intégrande :
f(z+r*exp(iθ))*exp(-inθ)

**Comment by R-Alexandre** [comment]
Merci
